"""add user foreign key to resumes

Revision ID: 2770c292bcd8
Revises: 03951cc2af7d
Create Date: 2026-08-18 16:30:34.859796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2770c292bcd8'
down_revision: Union[str, Sequence[str], None] = '03951cc2af7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('resumes_user_id_fkey', 'resumes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resumes_user_id_fkey', 'resumes', type_='foreignkey')
    # ### end Alembic commands ###
